# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.AddField(
            model_name='users',
            name='affiliate_channel',
            field=models.CharField(default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='affiliate_provider',
            field=models.CharField(default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='first_affiliate_tracked',
            field=models.CharField(default='untracked', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER'), ('Do not provide', '-unknown-')], default='Do not provide', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='signup_app',
            field=models.CharField(default='Web', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='signup_method',
            field=models.CharField(default='basic', max_length=20),
        ),
    ]
