# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True)),
                ('language', models.CharField(choices=[('en', 'english'), ('de', 'german'), ('it', 'italian'), ('ot', 'others')], default='en', max_length=100)),
            ],
        ),
    ]
