# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20161128_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
                ('location_1', models.CharField(blank=True, choices=[('us', 'US'), ('de', 'Germany'), ('au', 'Australia'), ('ca', 'Canada'), ('fr', 'France'), ('gb', 'Britain'), ('es', 'Spain'), ('pt', 'Portugal'), ('nl', 'Netherlands'), ('ot', 'Others')], default='us', max_length=100)),
                ('location_2', models.CharField(blank=True, choices=[('us', 'US'), ('de', 'Germany'), ('au', 'Australia'), ('ca', 'Canada'), ('fr', 'France'), ('gb', 'Britain'), ('es', 'Spain'), ('pt', 'Portugal'), ('nl', 'Netherlands'), ('ot', 'Others')], default='de', max_length=100)),
                ('location_3', models.CharField(blank=True, choices=[('us', 'US'), ('de', 'Germany'), ('au', 'Australia'), ('ca', 'Canada'), ('fr', 'France'), ('gb', 'Britain'), ('es', 'Spain'), ('pt', 'Portugal'), ('nl', 'Netherlands'), ('ot', 'Others')], default='au', max_length=100)),
                ('location_4', models.CharField(blank=True, choices=[('us', 'US'), ('de', 'Germany'), ('au', 'Australia'), ('ca', 'Canada'), ('fr', 'France'), ('gb', 'Britain'), ('es', 'Spain'), ('pt', 'Portugal'), ('nl', 'Netherlands'), ('ot', 'Others')], default='ca', max_length=100)),
                ('location_5', models.CharField(blank=True, choices=[('us', 'US'), ('de', 'Germany'), ('au', 'Australia'), ('ca', 'Canada'), ('fr', 'France'), ('gb', 'Britain'), ('es', 'Spain'), ('pt', 'Portugal'), ('nl', 'Netherlands'), ('ot', 'Others')], default='fr', max_length=100)),
            ],
            options={
                'ordering': ('account',),
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER'), ('-unknown-', '-unknown-')], default='-unknown-', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='location',
            field=models.CharField(blank=True, choices=[('us', 'US'), ('de', 'Germany'), ('au', 'Australia'), ('ca', 'Canada'), ('fr', 'France'), ('gb', 'Britain'), ('es', 'Spain'), ('pt', 'Portugal'), ('nl', 'Netherlands'), ('ot', 'Others')], default='us', max_length=100),
        ),
    ]
