# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20161031_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
