# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20161101_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='location',
            field=models.CharField(blank=True, choices=[('us', 'US'), ('de', 'Germany'), ('au', 'Austrilia'), ('ca', 'Canada')], default='us', max_length=100),
        ),
    ]
