# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_users_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
