# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_auto_20161130_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslocation',
            name='location_1',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('DE', 'Germany'), ('AU', 'Australia'), ('CA', 'Canada'), ('FR', 'France'), ('GB', 'Britain'), ('ES', 'Spain'), ('PT', 'Portugal'), ('NL', 'Netherlands'), ('other', 'Others')], default='US', max_length=100),
        ),
        migrations.AlterField(
            model_name='userslocation',
            name='location_2',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('DE', 'Germany'), ('AU', 'Australia'), ('CA', 'Canada'), ('FR', 'France'), ('GB', 'Britain'), ('ES', 'Spain'), ('PT', 'Portugal'), ('NL', 'Netherlands'), ('other', 'Others')], default='DE', max_length=100),
        ),
        migrations.AlterField(
            model_name='userslocation',
            name='location_3',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('DE', 'Germany'), ('AU', 'Australia'), ('CA', 'Canada'), ('FR', 'France'), ('GB', 'Britain'), ('ES', 'Spain'), ('PT', 'Portugal'), ('NL', 'Netherlands'), ('other', 'Others')], default='AU', max_length=100),
        ),
        migrations.AlterField(
            model_name='userslocation',
            name='location_4',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('DE', 'Germany'), ('AU', 'Australia'), ('CA', 'Canada'), ('FR', 'France'), ('GB', 'Britain'), ('ES', 'Spain'), ('PT', 'Portugal'), ('NL', 'Netherlands'), ('other', 'Others')], default='CA', max_length=100),
        ),
        migrations.AlterField(
            model_name='userslocation',
            name='location_5',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('DE', 'Germany'), ('AU', 'Australia'), ('CA', 'Canada'), ('FR', 'France'), ('GB', 'Britain'), ('ES', 'Spain'), ('PT', 'Portugal'), ('NL', 'Netherlands'), ('other', 'Others')], default='FR', max_length=100),
        ),
    ]
