# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German'), ('it', 'Italian'), ('ot', 'Others')], default='en', max_length=100),
        ),
    ]
